---
abstract: 'Automatic OO wrapping of container references'
author:
  - 'William Cox <mydimension@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Ref
no_index:
  package:
    - Class::Ref::HASH
    - Class::Ref::HASH::Tie
    - Class::Ref::ARRAY
    - Class::Ref::ARRAY::Tie
    - Class::Ref::CODE
    - Class::Ref::REF
    - Class::Ref::SCALAR
    - Class::Ref::LVALUE
    - Class::Ref::VSTRING
    - Class::Ref::GLOB
    - Class::Ref::FORMAT
    - Class::Ref::IO
provides:
  Class::Ref:
    file: lib/Class/Ref.pm
    version: 0.01
  Class::Ref::ARRAY:
    file: lib/Class/Ref.pm
    version: 0
  Class::Ref::ARRAY::Tie:
    file: lib/Class/Ref.pm
    version: 0
  Class::Ref::HASH:
    file: lib/Class/Ref.pm
    version: 0
  Class::Ref::HASH::Tie:
    file: lib/Class/Ref.pm
    version: 0
requires:
  Carp: 0
  Scalar::Util: 0
  perl: v5.6.1
resources:
  bugtracker: https://github.com/mydimension/Class-Ref/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/mydimension/Class-Ref.git
version: 0.01
